logging:
  structured:
    format:
      console: json
      file: json
  json:
    console:
      enabled: true
    file:
      enabled: true

spring:
  application:
    name: orders-orchestrator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${GROUP_ID:orders-orchestrator}
      fetch-min-bytes: ${FETCH_MIN_BYTES:262144}
      fetch-max-wait-ms: ${FETCH_MAX_WAIT_MS:100}
      max-poll-records: ${MAX_POLL_RECORDS:1000}
      properties:
        max.partition.fetch.bytes: ${MAX_PARTITION_FETCH_BYTES:10485760}
    producer:
      transaction-id-prefix: orders-tx-
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/orch?reWriteBatchedInserts=true}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    hikari:
      connection-timeout: 250
      validation-timeout: 250
      maximum-pool-size: 8

orchestrator:
  failure-mode: ${FAILURE_MODE:ATOMIC}        # ATOMIC | SKIP_AND_LOG
  non-atomic-max-attempts: ${NON_ATOMIC_MAX_ATTEMPTS:3}
  consumer-topic: ${SOURCE_TOPIC:orders.raw}
  producer-topic: ${TARGET_TOPIC:orders.enriched}
  group-id: ${GROUP_ID:orders-orchestrator}
  batch-enabled: true
  consumer-concurrency: ${CONCURRENCY:6}
  db-strategy: ${DB_STRATEGY:RELIABLE}        # OUTBOX | RELIABLE | LIGHTWEIGHT | NONE
  error-table: ${ERROR_TABLE:event_failures}
  db-timeout-ms: ${DB_TIMEOUT_MS:150}
  db-degrade-dont-block: true
  db-circuit-failure-threshold: ${DB_CIRCUIT_FAILURE_THRESHOLD:5}
  db-circuit-open-ms: ${DB_CIRCUIT_OPEN_MS:10000}
  store-payload: ${STORE_PAYLOAD:NONE}         # NONE | BYTES | TEXT
  store-payload-on-failure-only: ${STORE_PAYLOAD_ON_FAILURE_ONLY:true}
  commit-batch-size: ${COMMIT_BATCH_SIZE:50}
  commit-flush-interval-ms: ${COMMIT_FLUSH_INTERVAL_MS:200}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
